steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/python-compatibility-tools/python27:${_TAG_PY27}', '.']
  id: build_py27
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/python-compatibility-tools/python27:${_TAG_PY27}']
  id: push_py27
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'images', 'add-tag', 'gcr.io/python-compatibility-tools/python27:${_TAG_PY27}', 'gcr.io/python-compatibility-tools/python27:latest']
  id: tag_py27
