apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    creationTimestamp: "2018-06-15T20:08:48Z"
    deployment.kubernetes.io/revision: "36"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"creationTimestamp":"2018-06-15T20:08:48Z","deployment.kubernetes.io/revision":"33"},"creationTimestamp":"2018-06-15T20:08:48Z","generation":98,"labels":{"run":"compatibility-server"},"name":"compatibility-server","namespace":"default","resourceVersion":"59364428","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/compatibility-server","uid":"ea4ab52b-70d7-11e8-8f57-42010a800003"},"spec":{"progressDeadlineSeconds":600,"replicas":10,"revisionHistoryLimit":10,"selector":{"matchLabels":{"run":"compatibility-server"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"run":"compatibility-server"}},"spec":{"containers":[{"image":"gcr.io/python-compatibility-tools/compatibility-server:v28","imagePullPolicy":"IfNotPresent","name":"compatibility-server","ports":[{"containerPort":8888,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/run/docker.sock","name":"docker-sock"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":310,"volumes":[{"hostPath":{"path":"/var/run/docker.sock","type":"File"},"name":"docker-sock"}]}}},"status":{"availableReplicas":10,"conditions":[{"lastTransitionTime":"2019-03-01T17:42:26Z","lastUpdateTime":"2019-03-09T17:38:22Z","message":"ReplicaSet \"compatibility-server-7bb97bfdc4\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2019-03-10T02:36:44Z","lastUpdateTime":"2019-03-10T02:36:44Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":98,"readyReplicas":10,"replicas":10,"updatedReplicas":10}}
  creationTimestamp: "2018-06-15T20:08:48Z"
  generation: 102
  labels:
    run: compatibility-server
  name: compatibility-server
  namespace: default
  resourceVersion: "127286413"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/compatibility-server
  uid: ea4ab52b-70d7-11e8-8f57-42010a800003
spec:
  progressDeadlineSeconds: 600
  replicas: 200
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: compatibility-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: compatibility-server
    spec:
      containers:
      - image: gcr.io/python-compatibility-tools/compatibility-image:v30
        imagePullPolicy: IfNotPresent
        name: compatibility-server
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 310
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: File
        name: docker-sock
status:
  availableReplicas: 200
  conditions:
  - lastTransitionTime: "2019-03-01T17:42:26Z"
    lastUpdateTime: "2019-06-10T21:44:33Z"
    message: ReplicaSet "compatibility-server-84769766f4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-06-11T20:55:19Z"
    lastUpdateTime: "2019-06-11T20:55:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 102
  readyReplicas: 200
  replicas: 200
  updatedReplicas: 200
