apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    creationTimestamp: 2018-06-15T20:08:48Z
    deployment.kubernetes.io/revision: "44"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"creationTimestamp":"2018-06-15T20:08:48Z","deployment.kubernetes.io/revision":"41"},"creationTimestamp":"2018-06-15T20:08:48Z","generation":108,"labels":{"run":"compatibility-server"},"name":"compatibility-server","namespace":"default","resourceVersion":"128704700","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/compatibility-server","uid":"ea4ab52b-70d7-11e8-8f57-42010a800003"},"spec":{"progressDeadlineSeconds":600,"replicas":200,"revisionHistoryLimit":10,"selector":{"matchLabels":{"run":"compatibility-server"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"run":"compatibility-server"}},"spec":{"containers":[{"image":"gcr.io/python-compatibility-tools/compatibility-image:v31","imagePullPolicy":"IfNotPresent","name":"compatibility-server","ports":[{"containerPort":8888,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/run/docker.sock","name":"docker-sock"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":310,"volumes":[{"hostPath":{"path":"/var/run/docker.sock","type":"File"},"name":"docker-sock"}]}}},"status":{"availableReplicas":200,"conditions":[{"lastTransitionTime":"2019-06-13T15:32:29Z","lastUpdateTime":"2019-06-13T15:32:29Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2019-06-12T00:53:51Z","lastUpdateTime":"2019-06-13T17:01:09Z","message":"ReplicaSet \"compatibility-server-6484ffd4f6\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":108,"readyReplicas":200,"replicas":200,"updatedReplicas":200}}
  creationTimestamp: 2018-06-15T20:08:48Z
  generation: 111
  labels:
    run: compatibility-server
  name: compatibility-server
  namespace: default
  resourceVersion: "128786447"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/compatibility-server
  uid: ea4ab52b-70d7-11e8-8f57-42010a800003
spec:
  progressDeadlineSeconds: 600
  replicas: 200
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: compatibility-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: compatibility-server
    spec:
      containers:
      - image: gcr.io/python-compatibility-tools/compatibility-image:v33
        imagePullPolicy: IfNotPresent
        name: compatibility-server
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 310
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: File
        name: docker-sock
status:
  availableReplicas: 200
  conditions:
  - lastTransitionTime: 2019-06-13T19:21:20Z
    lastUpdateTime: 2019-06-13T19:21:20Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-06-12T00:53:51Z
    lastUpdateTime: 2019-06-13T19:21:30Z
    message: ReplicaSet "compatibility-server-589994f6bc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 111
  readyReplicas: 200
  replicas: 200
  updatedReplicas: 200
