apiVersion: v1
kind: Service
metadata:
  name: compatibility-server-service
  labels:
    run: compatibility-server
spec:
  ports:
  - port: 80
    targetPort: 8888
  selector:
    run: compatibility-server
  type: LoadBalancer
  loadBalancerIP: $PROJECT_IPADDRESS
