apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: badge-server-cluster
spec:
  replicas: 10
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: badge-server-cluster
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: bigquery-key
      containers:
      - image: gcr.io/python-compatibility-tools/badge_server:ver11
        imagePullPolicy: IfNotPresent
        name: badge-server-cluster
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
